import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import bgImage from "../../public/Paint-2.webp";
import Logo from "../../public/airco-main.png";

export default function Home(): NextPage {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="flex min-h-screen flex-col items-center bg-cover bg-fixed bg-right bg-no-repeat"
        style={{ backgroundImage: `url(${bgImage.src})` }}
      >
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <Image
            src="/airco-main.png"
            alt="primary Logo"
            width="450"
            height="100"
          />
          <div className="grid grid-cols-2 gap-8 sm:grid-cols-4 md:gap-12">
            <Image
              src="/airco-main.png"
              alt="primary Logo"
              width="200"
              height="100"
            />
            <Image
              src="/airco-main.png"
              alt="primary Logo"
              width="200"
              height="100"
            />
            <Image
              src="/airco-main.png"
              alt="primary Logo"
              width="200"
              height="100"
            />
            <Image
              src="/airco-main.png"
              alt="primary Logo"
              width="200"
              height="100"
            />
          </div>

          <div className="mt-8 max-w-5xl text-center">
            <h1 className=" text-6xl font-bold">Under Construction</h1>
            <p className="mt-8 text-lg font-medium">
              Airco specializes in the application of both powder and liquid
              coatings. We provide abrasive blasting, fireproofing, and linings,
              applied both in a shop environment or at your site. Our team of
              experts ensures finishes that are durable, have a long life cycle,
              and are done to the highest safety and quality standards, all
              within your time frame and budget. Please contact us below for
              immediate assistance. You can trust Airco for all your surface
              preparation and finishing requirements
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
